typography_spectrum: 0.009117587236687541
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2585503419395536
  lightness: 0.567444359883666
  saturation: 0.08369789365679026
  rhythmicContrast: 0.16720444639213383
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05203065602108836
analytics:
  google: null
  facebook: null
  twitter: null
name: Form Language Ltd
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WORDS WITH IMPACT
purpose: []
